services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Adapter\Framework\Command\:
        resource: '%kernel.project_dir%/src/Adapter/Framework/Command/*'

    App\Adapter\Framework\Persistence\:
        resource: '%kernel.project_dir%/src/Adapter/Framework/Persistence/*'

    App\Application\UseCase\:
        resource: '%kernel.project_dir%/src/Application/UseCase/*'

    App\Application\Service\:
        resource: '%kernel.project_dir%/src/Application/Service/*'

    App\Application\Service\FoodRepositoryProvider:
        arguments:
            $fruitRepository: '@App\Adapter\Framework\Persistence\InMemoryFruitRepository'
            $vegetableRepository: '@App\Adapter\Framework\Persistence\InMemoryVegetableRepository'
